sillsdev/saymore

- .gitignore
- src/SayMore/Model/ArchivingHelper.cs
- src/SayMore/SayMore.csproj
- src/SayMoreTests/SayMoreTests.csproj
- src/SayMoreTests/model/SessionArchivingTests.cs
When the project is exported the language used by the project is
retained and used if the language is undefined.
This change depends on https://github.com/sillsdev/libpalaso/pull/624
Card: trello.com/c/2daw3H2s
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/19)
> st378 Avoid setting Actor language to undefined.

- src/SayMore/Model/ArchivingHelper.cs
The information in these files needs to be put into the .imdi file
if it is to be included in the export.
card: https://trello.com/c/A4Z2PJH7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/24)
> St385- IMDI .meta files are not part of IMDI export

- DistFiles/Archiving/AccessProtocols.json
- DistFiles/Archiving/elar.html
- DistFiles/SayMore.es.tmx
- DistFiles/SayMore.fr.tmx
- DistFiles/SayMore.pt.tmx
- DistFiles/SayMore.ru.tmx
- DistFiles/SayMore.tr.tmx
The site https://www.soas.ac.uk/elar/using-elar/access-protocol/
outlines the updated ELAR protocol:
Open to unregistered visitors
all ordinary Users
Subscribers (requires depositor permission)
Card: https://trello.com/c/VGaP64Tv
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/42)
> St388 - Update ELAR protocol to OUS

- src/SayMore/Model/Project.cs
- src/SayMoreTests/model/ProjectTests.cs
This is an obsolete value, replaced by VernacularISO3CodeAndName and
AnalysisISO3CodeAndName some time ago.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/64)
> Remove Iso639Code from the project model

- src/SayMore/Model/ArchivingHelper.cs
Fall back to using the current UI language for export in that situation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/65)
> Don't crash IMDI export when working language not set

- src/SayMore/Model/ArchivingHelper.cs
Makes sure we get an actual language code, not one with locale or other subcategories.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/66)
> Before forcing 3-letter code, strip code suffixes

- src/SayMore/UI/Overview/ProjectMetadataScreen.Designer.cs
This was done essentially by changing the column styles in the table layout
used by the ProjectMetadataScreen control.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/67)
> Fix "About This Project" screen to not spread out so much

- src/SayMore/UI/ComponentEditors/SessionBasicEditor.Designer.cs
All of the Size and Location changes were made automatically by VS 2017
before I touched anything in Designer.  The _participants settings have
the three actual changes I made.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/68)
> Click in Sessions:People field now opens the Participant editor

- src/SayMore/Model/ArchivingHelper.cs
- src/SayMoreTests/model/SessionArchivingTests.cs
If a Person does not have a specified primary or mother tongue language, don't just assume it is the project vernacular language (in IMDI export)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/71)
> Don't use project language as default for Actor languages

- src/SayMore/Model/ArchivingHelper.cs
- src/SayMore/Model/Fields/ContributionSerializer.cs
- src/SayMore/Model/Files/FileType.cs
- src/SayMore/Model/Project.cs
- src/SayMore/Model/Session.cs
- src/SayMore/Program.cs
- src/SayMore/ProjectContext.cs
- src/SayMore/UI/ComponentEditors/BindingHelper.cs
- src/SayMore/UI/ComponentEditors/ContributorsEditor.cs
- src/SayMore/UI/ComponentEditors/SessionBasicEditor.cs
- src/SayMoreTests/SayMoreTests.csproj
- src/SayMoreTests/model/Data/MixedSession.session
- src/SayMoreTests/model/Data/OldSession.session
- src/SayMoreTests/model/Fields/ContributionCollectionTests.cs
- src/SayMoreTests/model/ProjectTests.cs
- src/SayMoreTests/model/SessionArchivingTests.cs
- src/SayMoreTests/model/SessionTests.cs
In general, attempts to remove use of the Participants list except to maintain it for backwards compatibility. Instead, we derive the data from Contributions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/81)
> Don't store roles as part of the file Participants list

- build/getDependencies-windows.sh
A recent update to L10NSharp introduced a breaking change to the continuous build of libpalaso.
```
ApplicationContainer.cs(198, 30): error CS0722: 'LocalizationManager': static types cannot be used as return types
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/96)
> Tag libpalaso dependency for master branch

- src/SayMore/Transcription/UI/ExportToFieldWorksInterlinearDlg.cs
Getting "The file 'C:\ProgramData\SIL\WritingSystemStore\bn.ldml.bad' already exists" exception if there is a problem migrating a writing system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/97)
> Do not crash if there is an error migrating a writing system

- src/Installer/Installer.wxs
The version of Microsoft.Extensions.DependencyModel.dll shipping with Fieldworks is not compatible with SayMore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/102)
> SP-2118: FieldWorks installs an incompatible version

- src/SayMoreTests/Transcription/Model/TimeTierTests.cs
This segment boundary test was failing in some environments due to floating-point error
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/107)
> Segment boundary test failing

- src/SayMore/UI/Overview/Statistics/StatisticsViewModel.cs
i.MediaFilePath will be empty if the file is zero length. This happens often with the generated oral annotation file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/115)
> SP-2171: Object reference error opening progress form

- src/SayMore/Model/Files/ComponentFile.cs
- src/SayMore/UI/ComponentEditors/ContributorsEditor.cs
- src/SayMore/UI/ElementListScreen/ComponentFileGrid.cs
and ContributorsEditor data is not in valid state
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/122)
> SP-2186: Prevent crash when user tries to rename component file

- build/SayMore.proj
Without this, the release build does not get this named and copied to the correct location and the new build does not appear on the download site.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/124)
> Added UpdateDownloadInfo target as dependency on Installer

- src/SayMore/Model/Session.cs
This can happen when a session is disposed, but a late OnPaint accesses that method
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/130)
> SP-2216: Added check for null MetaDataFile  in GetShouldReportHaveConsent

- src/SayMore/UI/ElementListScreen/ComponentFileGrid.cs
- src/SayMore/UI/Overview/ProjectDocsScreen.cs
Excluded files that appear to be MS Office temp files from Project docs list. Also, made file list a read-only collection so that underlying file system changes could not occur undetected, leading to crashes when working with the ComponentFile grid.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/135)
> SP-2333: Prevented undesirable behavior related to MS Office temp files

- DistFiles/SayMore.es.tmx
- DistFiles/SayMore.fr.tmx
- DistFiles/SayMore.pt.tmx
- DistFiles/SayMore.ru.tmx
- DistFiles/SayMore.tr.tmx
- DistFiles/SayMore.zh-Hans.tmx
- src/SayMore/ApplicationContainer.cs
- src/SayMore/UI/ComponentEditors/BrowserEditor.cs
- src/SayMore/UI/Overview/ProjectDocsScreen.cs
- src/SayMore/UI/ProjectWindow/ProjectWindow.cs
Also prevented crash caused by trying to copy a file over itself and made program more robust by reporting other file copy errors instead of crashing.
Added lines to log file to be able to know which UI locale is in use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/138)
> SP-2240: Fixed internationalization/localization problems that led to crash

- DistFiles/SayMore.es.tmx
- DistFiles/SayMore.fr.tmx
- DistFiles/SayMore.pt.tmx
- DistFiles/SayMore.ru.tmx
- DistFiles/SayMore.tr.tmx
- DistFiles/SayMore.zh-Hans.tmx
- SayMore.sln.DotSettings
- src/SayMore/UI/ComponentEditors/BindingHelper.cs
- src/SayMore/UI/ComponentEditors/ContributorsEditor.cs
- src/SayMore/UI/ComponentEditors/SessionBasicEditor.cs
- src/SayMore/UI/ElementListScreen/ComponentFileGrid.cs
- src/SayMore/UI/ElementListScreen/ElementGrid.cs
- src/SayMore/UI/ElementListScreen/ElementListScreen.cs
- src/SayMore/UI/ElementListScreen/SessionsListScreen.cs
- src/SayMore/UI/LowLevelControls/ListPanel.cs
- src/SayMore/UI/ProjectWindow/ViewButtonManager.cs
Despite validation errors, SayMore would allow the user to go ahead with changing to a different view, task, etc. that would lead to an exception: Operation did not succeed because the program cannot commit or quit a cell value change.
Note that I was not able to reproduce SP-2186/SP-2265 in the current version, but I did determine that the previous fix for SP-2186 was actually for a different scenario that caused the same exception. I suspect that some subsequent change actually fixed the problem, but even if not, it's possible that this fix will.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/144)
> SP-995, SP-2186, SP-2144: Fixed various scenarios leading to "Operation did not succeed"

- src/SayMore/UI/ElementListScreen/ComponentFileGrid.cs
Although I was not able to reproduce this error (it is several years old, and possibly some other fix now makes it impossible), it seemed best to check the index rather than blindly accessing a potentially nonexistent element merely for the sake of being able to re-select it later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/145)
> SP-1760: Added defensive code to prevent argument out of range error

- src/SayMore/Transcription/UI/TextAnnotationGrid/AudioWaveFormColumn.cs
- src/SayMore/Transcription/UI/TextAnnotationGrid/TierColumnBase.cs
Also check for a null grid before accessing it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/156)
> SP-1769: Prevent changing the grid while executing PlaybackProgressReportAction

- src/SayMore/MediaUtils/MPlayer/MPlayerHelper.cs
- src/SayMore/MediaUtils/MPlayer/MediaPlayer.cs
- src/SayMore/Transcription/UI/ComponentEditors/ConvertToStandardAudioEditor.cs
Added code to catch InvalidAsynchronousStateException during media playback which I think is happening when trying to invoke on the UI thread during a shutdown or crash.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/166)
> Fixed problem with logger for media playback

- DistFiles/SayMore.es.xlf
- DistFiles/aboutBox.htm
- DistFiles/releaseNotes.md
- build/SayMore.proj
- src/SayMore/Properties/AssemblyInfo.cs
- src/SayMore/SayMore.csproj
- src/SayMore/Transcription/Model/AnnotationFileHelper.cs
- src/SayMore/Transcription/Model/Exporters/PlainTextTranscriptionExporter.cs
- src/SayMore/Transcription/UI/CommonUIStrings.cs
- src/SayMore/Transcription/UI/ComponentEditors/ConvertToStandardAudioEditor.cs
- src/SayMore/Transcription/UI/ComponentEditors/StartAnnotatingEditor.Designer.cs
- src/SayMore/Transcription/UI/ComponentEditors/StartAnnotatingEditor.cs
- src/SayMore/Transcription/UI/ExportToFieldWorksInterlinearDlg.cs
- src/SayMore/UI/ElementListScreen/ElementListScreen.cs
- src/SayMore/UI/SplashScreenForm.Designer.cs
Requested here: https://community.software.sil.org/t/saymore-import-of-audacity-track-label-can-we-have-it-go-to-free-translation/7095/5
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/170)
> Added option to import Audacity labels into free translation

- src/SayMore/MediaUtils/Audio/AudioUtils.cs
- src/SayMore/MediaUtils/MPlayer/MPlayerHelper.cs
- src/SayMore/ProjectContext.cs
Changed to use FFmpeg as primary and Mplayer as secondary. Added command-line switch to MPlayer to prevent conversion of media to IEEE float WAV files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/174)
> SP-2303: Fixed process to convert source media to standard PCM WAV files

- src/SayMore/MediaUtils/MPlayer/MediaPlayer.cs
Changed sequence of setup operations in MediaPlayer to prevent setting handlers that might be called and Invoke an operation before the window handle is created.
Note: I have not found a way to reproduce this crash, but it was reported twice by the same user in quick succession.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/176)
> SP-2307: prevent Invoke before MediaPlayer window handle is created

- .gitignore
- DistFiles/FFmpeg/.guidsForInstaller.xml
- build/SayMore.proj
- build/TestInstallerBuild.bat
- src/template.releasenotes.download_info
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/177)
> Added build target to convert release notes to HTML

- src/SayMore/MediaUtils/Audio/WaveControls/WaveControlBasic.cs
- src/SayMore/Transcription/UI/ComponentEditors/OralAnnotationEditor.cs
Also fixed problem that prevented playing regenerated file.
Included some Resharper-suggested code cleanup.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/184)
> SP-2332: Prevented NullReferenceException when clicking away during playback of generated oral annotations

- src/SayMore/Transcription/UI/SegmentingAndRecording/OralAnnotationRecorderDlgBase.cs
The fix (long time ago) seems to have worked, and we don't need all these now pointless events coming in to analytics.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/215)
> Remove diagnostic code to log and report analytics for SP-950.

- src/SayMore/Properties/AssemblyInfo.cs
This gets the copyright symbol to render in the splash screen in the installed version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/216)
> Changed AssemblyInfo.cs to be encoded as UTF-8

- DistFiles/releaseNotes.md
- build/SayMore.proj
- src/SayMore/MediaUtils/MPlayer/VideoPanel.cs
- src/SayMore/Transcription/UI/TextAnnotationGrid/TextAnnotationEditorGrid.cs
SP-2306: This most likely solves problem of the first cell getting focus unexpectedly on Mac running via Parallels.
It also solves a deadlock when right-clicking to display the context menu.
Probably generally avoids other potential deadlock situations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/217)
> Solve undesirable behavior and deadlocks in text annotation grid

- src/SayMore/Transcription/UI/TextAnnotationGrid/TextAnnotationEditorGrid.cs
This can lead to an ArgumentOutOfRangeException
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/218)
> SP-2360: Do not set FirstDisplayedScrollingRowIndex during layout

- src/SayMore/Model/Files/XmlFileSerializer.cs
- src/SayMoreTests/model/Files/FileSerializerTests.cs
With this change, XML comments added by the user will be ignore (though they will not be preserved when saving).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/222)
> SP-2367, SP-2241, SP-2179: Made XmlFileSerializer.Load more robust

- src/SayMore/UI/ElementListScreen/ComponentFileGrid.cs
- src/SayMore/UI/ElementListScreen/ElementListScreen.cs
Added PrepareToSelectDifferentFile event in ComponentFileGrid so that subscribers can be alerted. In ElementListScreen, handled that event by informing current editor to prepare to deactivate. In the case of the OralAnnotationEditor, this allows it to stop playback in a timely fashion.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/228)
> SP-913: Stop playback of combined oral annotation audio when another file is chosen

- DistFiles/SayMore.es.xlf
- DistFiles/SayMore.fr.xlf
- DistFiles/SayMore.pt.xlf
- DistFiles/SayMore.ru.xlf
- DistFiles/SayMore.tr.xlf
- DistFiles/releaseNotes.md
- src/SayMore/Transcription/UI/ExportToFieldWorksInterlinearDlg.Designer.cs
- src/SayMore/Transcription/UI/ExportToFieldWorksInterlinearDlg.cs
- src/SayMore/Transcription/UI/ExportToFieldWorksInterlinearDlg.resx
Though not a "fix" for SP-2378, that issue inspired this improvement. Made a small tweak to the logic to select the correct writing system for translations when the user has set the analysis WS in SayMore. Also made some internationalization/localization improvements in this area of the code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/236)
> Added a label with instructions about importing flextext file into Flex

- build/SayMore.proj
- src/SayMore/MediaUtils/MPlayer/MediaPlayerViewModel.cs
- src/SayMoreTests/UI/Charts/ChartBarInfoTests.cs
- src/SayMoreTests/UI/ComponentEditors/EditorBaseTests.cs
- src/SayMoreTests/UI/ProjectWindow/ReleaseNotesCommandTests.cs
- src/SayMoreTests/packages.config
Bug: If you click in the last row of the annotations grid and then quickly press mouse down before the playback starts, SayMore will think it needs to wait until the playback ends and will appear to hang until it has waited for the entire duration of the audio file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/239)
> SP-2388:  Fixed hang in text annotations
