- build/SayMore.proj
- build/getDependencies-windows.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/8)
> Use SIL.BuildTasks

- src/SayMore/UI/ElementListScreen/ElementGrid.cs
- src/SayMoreTests/model/SessionWorkflowInformantTests.cs
This depends on https://github.com/sillsdev/l10nsharp/pull/23 and should not be merged until that PR is merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/13)
> Fixed up unit tests to work with improved version of L10NSharp.

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/14)
> Update links in readme file.

- src/SayMore/Model/ArchivingHelper.cs
- src/SayMore/Properties/AssemblyInfo.cs
- src/SayMoreTests/model/SessionArchivingTests.cs
Calculate age based on birth year.
trello.com/c/VJcAs7lg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/18)
> IMDI fix age validation error

- .gitignore
- src/SayMore/Model/ArchivingHelper.cs
- src/SayMore/SayMore.csproj
- src/SayMoreTests/SayMoreTests.csproj
SIL Core is using .net core and reporting moved to SIL Desktop
We need to include SIL Desktop with in our build
Interface changes related to st380 are made on SIL Core
see card: https://trello.com/c/IlOdLSNy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/32)
> netCore - update project for latest SIL Core library

- src/SayMore/Model/ArchivingHelper.cs
- src/SayMore/Model/Files/AnnotationComponentFile.cs
- src/SayMore/Model/Files/ComponentFile.cs
- src/SayMore/Model/Files/ProjectElementComponentFile.cs
- src/SayMoreTests/Transcription/UI/OralAnnotationRecorderDlgViewModelTests.cs
- src/SayMoreTests/Transcription/UI/SegmenterDlgBaseViewModelTests.cs
- src/SayMoreTests/model/SessionArchivingTests.cs
Get the file object and attach RecordingEquipment keywords for
recording device and microphone.
Depends on: sillsdev/libpalaso#653
card: https://trello.com/c/IlOdLSNy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/22)
> St384 - output recording device and microphone as recordingEquipment

- src/SayMore/Model/ArchivingHelper.cs
- src/SayMoreTests/model/SessionArchivingTests.cs
Depends on https://github.com/sillsdev/libpalaso/pull/645
Card: trello.com/c/pWsf8i6D
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/21)
> St380 Include ethnic group in IMDI export

- src/Installer/Installer.wxs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/34)
> Add SIL.Core.Desktop to installer

- src/SayMore/Model/ArchivingHelper.cs
- src/SayMoreTests/model/SessionArchivingTests.cs
Allow Topic and Keyword as values without custom_ prefix
Use How to contact as actor address
Add actor, content, and resource descriptions
User UI language as analysis language
Put Code in actor's data
Card: https://trello.com/c/hgZrUmAB
Depends on: sillsdev/libpalaso#657
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/25)
> St386 - add properties, fields and notes from meta files

- src/SayMore/Model/ArchivingHelper.cs
- src/SayMoreTests/model/SessionArchivingTests.cs
These can be entered as special custom fields and
will show up as Keys in the IMDI export
card: https://trello.com/c/l1YrFRfB
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/35)
> st383 - Add ELAR Topic and ELAR Keyword(s)

- src/SayMoreTests/model/SessionWorkflowInformantTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/45)
> Revert test logic based on update to SIL Core library

- DistFiles/SayMore.tr.tmx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/47)
> Update Turkish localization

- src/SayMore/Model/Project.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/49)
> Allow zip to create larger files.

- .gitignore
- build/SayMore.proj
- build/getDependencies-windows.sh
- src/SayMore/SayMore.csproj
- src/SayMore/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/50)
> Update location of SIL.BuildTasks

- build/SayMore.proj
- src/SayMore/SayMore.csproj
- src/SayMore/packages.config
This reverts commit f7fecca523a597d0eae1ec96ef440e782c7fbe38.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/52)
> Revert "Use original SIL.BuildTasks with Split method (#51)"

- src/SayMore/Model/ArchivingHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/53)
> Force 3 letter code for analysis langauge on IMDI export

- src/SayMore/Model/ArchivingHelper.cs
- src/SayMore/SayMore.csproj
- src/SayMore/packages.config
Update BuildTasks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/54)
> Force all language codes in IMDI Archiving to 3 characters

- build/SayMore.proj
- src/SayMore/Properties/AssemblyInfo.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/59)
> Update version and copyright.

- DistFiles/aboutBox.htm
- DistFiles/releaseNotes.md
- src/SayMore/BuildType.cs
- src/SayMore/UI/SplashScreenForm.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/61)
> Update Release notes, about screen, splash screen and release type.

- .gitignore
- build/SayMore.proj
- build/TestInstallerBuild.bat
- src/Installer/Installer.wxs
- src/SayMore/Model/ArchivingHelper.cs
- src/SayMore/Properties/AssemblyInfo.cs
- src/SayMore/SayMore.csproj
- src/SayMore/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/62)
> Use DotNetZip. Fix SP-1818. Make build able to restore SilBuildTasks.

- build/getDependencies-windows.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/63)
> Updated getDependencies to reflect recent changes on TeamCity

- src/SayMore/UI/ComponentEditors/SessionBasicEditor.Designer.cs
- src/SayMore/UI/ComponentEditors/SessionBasicEditor.resx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/70)
> Align the second column of controls in SessionBasicEditor

- src/SayMore/Model/ArchivingHelper.cs
- src/SayMoreTests/model/SessionArchivingTests.cs
Also adds language attribute to Description
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/72)
> Output IMDI Project information as part of Session

- README.md
This change would allow users to know where to go for support
rather than going to the SIL site and looking for the link there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/17)
> Reference the community help site here.

- src/SayMore/SayMore.csproj
- src/SayMore/app.config
- src/SayMore/packages.config
- src/SayMoreTests/SayMoreTests.csproj
- src/SayMoreTests/app.config
- src/SayMoreTests/packages.config
This fixes Writing System bug when exporting a session to FLEx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/73)
> SP-1826: Updated/added required packages for compatibility with libpalaso 5

- src/SayMoreTests/model/SessionArchivingTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/74)
> Fix tests broken by having complete ISO 639-2 data available

- src/SayMore/Model/ArchivingHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/76)
> SP-1828 Fix null ref exporting isolated session

- build/SayMore.proj
- src/SayMore/Model/ArchivingHelper.cs
- src/SayMoreTests/SayMoreTests.csproj
- src/SayMoreTests/SetupFixtureClass.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/78)
> Fix problems in unit tests caused by new Sldr init reqiuirement

- src/SayMore/Model/Session.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/83)
> Fix problem with session having no participants

- .nuget/NuGet.targets
- build/SayMore.proj
- src/SayMore/SayMore.csproj
- src/SayMoreTests/SayMoreTests.csproj
Removed some unnecessary VS2013 stuff for NuGet.
Improved proj file to allow it to be used for local test builds.
Made NuGet.targets more like the versions used in other projects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/84)
> NuGet cleanup and minor build improvements

- DistFiles/aboutBox.css
- DistFiles/aboutBox.htm
Update copyright date and links to other sites
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/89)
> Update the information in the About Box

- build/SayMore.proj
This has been tested and is ready to merge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/91)
> Set the msi name rather than the random file name

- .nuget/NuGet.targets
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/92)
> Fix path after nuget.exe update

- src/SayMore/Model/Files/XmlFileSerializer.cs
- src/SayMore/Model/Person.cs
- src/SayMore/UI/ComponentEditors/BindingHelper.cs
Was getting Directory not found. After that was fixed, started getting object not set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/93)
> Fix crashes when the last session or person are deleted

- src/SayMore/Transcription/UI/ExportToFieldWorksInterlinearDlg.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/95)
> Update FLEx export to handle the new Writing System repository location

- src/SayMore/ApplicationContainer.cs
- src/SayMore/MediaUtils/FFmpeg/FFmpegConversionInfo.cs
- src/SayMore/MediaUtils/MPlayer/MPlayerHelper.cs
- src/SayMore/MediaUtils/MediaFileInfo.cs
- src/SayMore/Model/Fields/FieldTemplate.cs
- src/SayMore/Model/Fields/GenreDefinition.cs
- src/SayMore/Program.cs
- src/SayMore/Transcription/Model/AnnotationFileHelper.cs
- src/SayMore/UI/ConvertMediaDlgViewModel.cs
- src/SayMore/UI/Overview/ProjectAccessScreen.cs
- src/SayMore/UI/ProjectWindow/ProjectWindow.cs
- src/SayMore/UI/ProjectWindow/ReleaseNotesCommand.cs
- src/SayMore/Utilities/FileSystemUtils.cs
- src/SayMoreTests/ShrinkProject.cs
Replace obsolete `SIL.IO.FileLocator` with `SIL.IO.FileLocationUtilities`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/98)
> Replace obsolete `SIL.IO.FileLocator`

- build/getDependencies-windows.sh
- src/Installer/Installer.wxs
- src/SayMore/ApplicationContainer.cs
- src/SayMore/SayMore.csproj
- src/SayMore/Transcription/UI/SegmentingAndRecording/OralAnnotationRecorderDlgBase.cs
- src/SayMore/Transcription/UI/SegmentingAndRecording/SegmenterDlgBase.cs
- src/SayMore/UI/ComponentEditors/EditorBase.cs
- src/SayMore/UI/ElementListScreen/ComponentFileGrid.Designer.cs
- src/SayMore/UI/ElementListScreen/ComponentFileGrid.cs
- src/SayMore/UI/ElementListScreen/ElementListScreen.cs
- src/SayMore/UI/Overview/ProjectAccessScreen.Designer.cs
- src/SayMore/UI/Overview/ProjectAccessScreen.cs
- src/SayMore/UI/Overview/ProjectScreen.cs
- src/SayMore/UI/Overview/Statistics/StatisticsView.cs
- src/SayMore/UI/ProjectChoosingAndCreating/WelcomeDialog.Designer.cs
- src/SayMore/UI/ProjectChoosingAndCreating/WelcomeDialog.cs
- src/SayMore/UI/ProjectWindow/ProjectWindow.cs
- src/SayMore/UI/ProjectWindow/UILanguageDlg.cs
- src/SayMore/UI/SessionRecording/SessionRecorderDlg.cs
- src/SayMore/UI/SessionRecording/SessionRecorderDlg.designer.cs
- src/SayMore/app.config
- src/SayMore/packages.config
- src/SayMoreTests/app.config
- src/SayMoreTests/model/SessionWorkflowInformantTests.cs
This is using L10NSharp 4.0.1-beta0005
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/99)
> Update to L10NSharp 4.0

- src/SayMore/Model/Files/ExportCommand.cs
Also did some code clean-up and fixed several spelling mistakes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/101)
> SP-2116: ArgumentNullException when exporting sessions

- src/SayMore/ApplicationContainer.cs
- src/SayMore/Program.cs
- src/SayMore/SayMore.csproj
- src/SayMore/Transcription/UI/SegmentingAndRecording/SegmenterDlgBaseViewModel.cs
- src/SayMore/UI/ConvertMediaDlgViewModel.cs
- src/SayMore/Utilities/FileSyncHelper.cs
- src/SayMore/Utilities/FileSystemUtils.cs
- src/SayMoreTests/SayMoreTests.csproj
- src/SayMoreTests/Utilities/FileSyncHelperTests.cs
- src/SayMoreTests/Utilities/FileSystemUtilsTests.cs
Includes Dropbox, Google Drive and Microsoft OneDrive
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/100)
> Detect, stop and restart file sync clients

- src/SayMore/UI/Overview/ProjectMetadataScreen.Designer.cs
- src/SayMore/UI/ProjectWindow/ProjectWindow.cs
- src/SayMore/Utilities/ExtensionMethods.cs
Pressing the Enter key in single line control should tab to next control rather than playing an "error sound."
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/104)
> SP-2112: Pressing Enter key in should tab to next control

- src/SayMore/Transcription/UI/ComponentEditors/OralAnnotationEditor.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/109)
> SP-2111: Oral annotations file not releasing when tab is closed

- src/SayMore/MediaUtils/Audio/WavePainting/WavePainterBasic.cs
Not able to reproduce, so I added a check for null and write to log if the value is null.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/110)
> SP-1799: Object reference not set to an instance of an object

- src/SayMore/ApplicationContainer.cs
- src/SayMore/Model/Files/DataGathering/AudioVideoDataGatherer.cs
- src/SayMore/Model/ProjectElement.cs
- src/SayMore/UI/Overview/Statistics/StatisticsViewModel.cs
- src/SayMoreTests/ApplicationContainerTests.cs
- src/SayMoreTests/SayMoreTests.csproj
- src/SayMoreTests/model/ProjectElementTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/105)
> SP-2114: Update data on the Project Progress tab

- build/SayMore.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/113)
> Removed “Upload” target (publishing now done via SSH Upload on TC)

- src/SayMore/UI/LowLevelControls/Slider.cs
- src/SayMoreTests/SayMoreTests.csproj
- src/SayMoreTests/UI/LowLevelControls/SliderTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/106)
> SP-2135: Do not throw fatal exception if slider value is out of range

- SayMore.sln.DotSettings
- src/SayMore/Transcription/UI/SegmentingAndRecording/OralAnnotationRecorderDlgBase.cs
- src/SayMore/Transcription/UI/SegmentingAndRecording/SegmenterDlgBase.cs
- src/SayMoreTests/Transcription/UI/SegmenterDlgBaseViewModelTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/116)
> SP-2174: Refactoring and addition of unit tests for GetButtonRectangleForSegment

- src/SayMore/Properties/Settings.Designer.cs
- src/SayMore/Properties/Settings.settings
- src/SayMore/Transcription/UI/SegmentingAndRecording/OralAnnotationRecorderDlgBase.cs
- src/SayMore/Transcription/UI/SegmentingAndRecording/SegmenterDlgBase.cs
- src/SayMore/UI/LowLevelControls/Slider.cs
- src/SayMore/app.config
- src/SayMoreTests/SayMoreTests.csproj
- src/SayMoreTests/UI/LowLevelControls/SliderTests.cs
Tester requested the minimum be reduced more. 0.46 was the smallest I could get and still have the UI display correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/114)
> SP-1000: Reduce minimum segment length from 0.5 seconds to 0.46

- src/SayMore/UI/Charts/ChartBarInfo.cs
- src/SayMore/UI/Charts/HTMLChartBuilder.cs
- src/SayMoreTests/UI/Charts/ChartBarInfoTests.cs
Also updated "By Stages" to "Completed Stages"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/117)
> SP-2114: Display time consistently as seconds on Progress tab

- src/SayMore/SayMore.csproj
- src/SayMore/packages.config
- src/SayMoreTests/SayMoreTests.csproj
- src/SayMoreTests/app.config
- src/SayMoreTests/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/123)
> SP-2193: Upgraded SIL DLLs to get fix for data error in Role column

- README.md
- src/SayMore/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/125)
> Updated email addresses to point to current SIL address

- src/SayMore/Transcription/UI/TextAnnotationGrid/AudioWaveFormColumn.cs
Duplicated issues: SP-2218/SP-2221/SP-2225/SP-2226
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/129)
> SP-2214: Avoid accessing Y on CurrentCellAddress when it is null.

- src/Installer/Installer.wxs
- src/SayMore/SayMore.csproj
- src/SayMore/packages.config
- src/SayMoreTests/SayMoreTests.csproj
- src/SayMoreTests/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/131)
> SP-2224: Replaced MarkdownDeep with Markdig.Signed

- src/SayMore/Model/Project.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/132)
> SP-2231: Added check to prevent crash when adding participants to RAMP archive

- build/SayMore.proj
- src/SayMore/Model/Files/ComponentFile.cs
- src/SayMore/Transcription/Model/TimeTier.cs
- src/SayMoreTests/Transcription/Model/TierCollectionTests.cs
- src/SayMoreTests/Transcription/Model/TimeTierTests.cs
- src/SayMoreTests/Transcription/UI/SegmenterDlgBaseViewModelTests.cs
- src/SayMoreTests/model/ProjectElementTests.cs
- src/SayMoreTests/model/ProjectTests.cs
[WIP] Started work on fixing tests broken by the last few changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/133)
> Made NUnit so it will fail when unit tests fail on Team City. And fix existing failures.

- SayMore.sln.DotSettings
- src/SayMore/MediaUtils/Audio/AudioFileHelper.cs
- src/SayMore/MediaUtils/Audio/WaveControls/WaveControlBasic.cs
- src/SayMore/MediaUtils/Audio/WaveControls/WaveControlWithBoundarySelection.cs
- src/SayMore/MediaUtils/Audio/WaveControls/WaveControlWithRangeSelection.cs
- src/SayMore/MediaUtils/Audio/WaveFileReaderWrapper.cs
- src/SayMore/MediaUtils/Audio/WavePainting/WavePainterBasic.cs
- src/SayMore/MediaUtils/Audio/WavePainting/WavePainterWithBoundarySelection.cs
- src/SayMore/MediaUtils/Audio/WavePainting/WavePainterWithRangeSelection.cs
- src/SayMore/Transcription/Model/AutoSegmenter.cs
- src/SayMore/Transcription/UI/SegmentingAndRecording/SegmenterDlgBase.cs
- src/SayMoreTests/Transcription/Model/AutoSegmenterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/134)
> SP-2197: Fixed crash when array with samples does not get filled

- src/SayMore/Transcription/UI/TextAnnotationGrid/TextAnnotationEditorGrid.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/140)
> SP-2219/SP-2220: Added some sanity check to try to prevent exception

- src/SayMore/MediaUtils/MPlayer/MediaPlayer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/139)
> SP-2222: Ensured updates to the slider time label happen on the UI thread

- SayMore.sln.DotSettings
- src/SayMore/Model/Fields/ContributionSerializer.cs
- src/SayMore/Model/Project.cs
- src/SayMore/Transcription/Model/AutoSegmenter.cs
- src/SayMore/Transcription/Model/Exporters/PlainTextTranscriptionExporter.cs
- src/SayMore/Transcription/UI/TextAnnotationGrid/TextAnnotationColumnWithMenu.cs
- src/SayMore/UI/ComponentEditors/SessionBasicEditor.cs
- src/SayMore/UI/ElementListScreen/ComponentFileGrid.cs
- src/SayMoreTests/Transcription/Model/AutoSegmenterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/137)
> Minor code cleanup and refactoring

- src/SayMore/Model/Project.cs
- src/SayMore/SayMore.csproj
- src/SayMore/Utilities/RobustFontHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/136)
> SP-2198: Handle problems in font settings string stored in sprj file

- .nuget/NuGet.targets
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/141)
> Removed section from NuGet.targets that was outdated and no longer needed

- src/SayMore/ProjectContext.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/142)
> SP-2254: Added info to log to make it easier to provide support when an XML file is corrupt

- src/SayMore/Model/ProjectElement.cs
- src/SayMore/ProjectContext.cs
These files are typically created by OSX
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/143)
> SP-2260: Avoid processing ._ meta files

- build/SayMore.proj
- src/SayMore/Properties/AssemblyInfo.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/148)
> Updated fallback BUILD_NUMBER property and copyright date.

- DistFiles/.guidsForInstaller.xml
- DistFiles/SayMore.ru.xlf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/151)
> Fixed XML errors that caused crash when trying to read Russian strings

- build/SayMore.proj
- src/Installer/Installer.wxs
- src/SayMore/SayMore.csproj
- src/SayMore/app.config
- src/SayMore/packages.config
- src/SayMoreTests/SayMoreTests.csproj
- src/SayMoreTests/app.config
- src/SayMoreTests/packages.config
Upgraded lots of DLLs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/152)
> Switched to SIL.DesktopAnalytics and fixed DLL issues with Newtonsoft.json

- src/SayMore/UI/SplashScreenForm.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/153)
> Fixed copyright date on splash screen

- build/SayMore.proj
- src/SayMore/SayMore.csproj
- src/SayMore/app.config
- src/SayMore/packages.config
- src/SayMoreTests/SayMoreTests.csproj
- src/SayMoreTests/app.config
- src/SayMoreTests/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/154)
> Upgraded SIL Dlls (and a few others)

- src/SayMore/SayMore.csproj
- src/SayMore/packages.config
- src/SayMoreTests/SayMoreTests.csproj
- src/SayMoreTests/app.config
- src/SayMoreTests/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/155)
> SP-2274: Upgraded SIL libraries to fix European decimal bug initializing SLDR

- src/Installer/Installer.wxs
This should enable viewing Release Notes without crashing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/158)
> SP-2279: Added System.Buffers to Installer

- build/SayMore.proj
- src/template.releasenotes.download_info
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/159)
> Added info about release notes so they can be published on website

- SayMore.sln.DotSettings
- src/SayMore/Model/Files/ComponentFile.cs
- src/SayMore/Model/Files/FileType.cs
- src/SayMore/SayMore.csproj
- src/SayMore/UI/ComponentEditors/ContributorsEditor.cs
- src/SayMore/UI/ComponentEditors/SessionBasicEditor.cs
- src/SayMore/UI/Overview/ProjectAccessScreen.cs
- src/SayMore/packages.config
- src/SayMoreTests/SayMoreTests.csproj
- src/SayMoreTests/app.config
- src/SayMoreTests/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/162)
> Change from Insite to REAP

- DistFiles/SayMore.es.xlf
- SayMore.sln.DotSettings
- src/SayMore/Model/ProjectElement.cs
- src/SayMore/UI/ComponentEditors/BindingHelper.cs
- src/SayMore/UI/ComponentEditors/PersonBasicEditor.cs
- src/SayMore/UI/ElementListScreen/ComponentFileGrid.cs
- src/SayMore/UI/ElementListScreen/ElementListScreen.cs
- src/SayMore/UI/ElementListScreen/ElementListViewModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/163)
> SP-2284 Prevent adding .session/.person files to an existing Session/Person

- SayMore.sln.DotSettings
- src/SayMore/Program.cs
- src/SayMore/UI/ProjectWindow/ProjectWindow.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/161)
> Added UI language to Analytics user info

- SayMore.sln.DotSettings
- src/SayMore/MediaUtils/MPlayer/MPlayerHelper.cs
- src/SayMore/MediaUtils/MPlayer/MediaPlayer.cs
- src/SayMore/MediaUtils/MPlayer/MediaPlayerViewModel.cs
- src/SayMore/Transcription/Model/TimeTier.cs
- src/SayMore/Utilities/FileSystemUtils.cs
- src/SayMoreTests/Utilities/FileSystemUtilsTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/168)
> Report condition where system volume is not set up to compute short names

- src/SayMore/SayMore.csproj
- src/SayMore/app.config
- src/SayMore/packages.config
- src/SayMoreTests/SayMoreTests.csproj
- src/SayMoreTests/app.config
- src/SayMoreTests/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/169)
> SP-2291: Fix when zipping large RAMP archives

- src/SayMore/SayMore.csproj
- src/SayMore/Transcription/Model/AnnotationFileHelper.cs
- src/SayMore/UI/ComponentEditors/ContributorsEditor.cs
- src/SayMore/packages.config
- src/SayMoreTests/SayMoreTests.csproj
- src/SayMoreTests/packages.config
Also, fix layout of Contributors editor so the delete column does not get hidden when the window is made narrow.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/171)
> SP-2297: Prevent crash when clearing contributor name and selecting next row

- SayMore.sln.DotSettings
- src/SayMore/Model/ElementRepository.cs
- src/SayMore/Model/PersonInformant.cs
- src/SayMore/UI/ComponentEditors/ContributorsEditor.cs
- src/SayMore/UI/Overview/ProjectMetadataScreen.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/175)
> SP-2304: Ensure initial column widths for People and Roles are adequate

- src/SayMore/SayMore.csproj
- src/SayMore/app.config
- src/SayMore/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/180)
> Upgrade desktop analytics

- src/Installer/Installer.wxs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/182)
> Added files to the installer that are now required by some of the new dependencies

- DistFiles/releaseNotes.md
- src/SayMore/Model/Project.cs
- src/SayMore/Program.cs
- src/SayMore/UI/ProjectChoosingAndCreating/NewProjectDialog/NewProjectDlgViewModel.cs
- src/SayMore/UI/ProjectChoosingAndCreating/WelcomeDialogViewModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/183)
> SP-2331: Fixed "Folder provided should be an existing directory" error when creating a new project

- SayMore.sln.DotSettings
- src/SayMore/Transcription/UI/SegmentingAndRecording/OralAnnotationRecorderDlgBase.cs
- src/SayMore/Transcription/UI/SegmentingAndRecording/OralAnnotationRecorderDlgViewModel.cs
- src/SayMore/Transcription/UI/SegmentingAndRecording/SegmenterDlgBase.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/187)
> Prevented waveform scrolling to the beginning after listening to a source segment

- SayMore.sln.DotSettings
- src/SayMore/Model/Fields/ContributionSerializer.cs
- src/SayMore/Model/Files/FileType.cs
- src/SayMore/Model/ProjectElement.cs
- src/SayMore/Model/Session.cs
- src/SayMore/Model/SessionContribution.cs
- src/SayMore/Program.cs
- src/SayMore/ProjectContext.cs
- src/SayMore/SayMore.csproj
- src/SayMore/UI/ComponentEditors/EditorBase.cs
- src/SayMore/UI/ComponentEditors/PersonContributionEditor.cs
- src/SayMoreTests/model/Fields/ContributionSerializerTests.cs
- src/SayMoreTests/model/SessionTests.cs
Also did a tiny amount of refactoring and code cleanup
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/191)
> Display person contribution details correctly

- DistFiles/releaseNotes.md
- src/Installer/Installer.wxs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/204)
> Added missing SIL.Windows.Forms.Archiving.DLL to Installer

- DistFiles/SayMore.es.xlf
- DistFiles/SayMore.fr.xlf
- DistFiles/SayMore.pt.xlf
- DistFiles/SayMore.ru.xlf
- DistFiles/SayMore.tr.xlf
- src/SayMore/Model/Files/ComponentFile.cs
- src/SayMore/UI/ShortFileNameWarningDlg.Designer.cs
Fixed one I18n problem
Changed one localizaed string to use parameters for SayMore
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/206)
> Updated localizations from Crowdin.

- src/SayMore/Model/Files/DataGathering/AutoCompleteValueGatherer.cs
- src/SayMore/UI/ComponentEditors/AutoCompleteHelper.cs
- src/SayMore/UI/ComponentEditors/PersonBasicEditor.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/207)
> Do not display language chooser if the user starts typing a name that matches an autocomplete option

- DistFiles/releaseNotes.md
- src/SayMore/UI/ComponentEditors/PersonBasicEditor.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/208)
> Fixed logic that checks for Autocomplete match to be case insensitive

- src/Installer/appcast.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/209)
> Changed URL in appcast.xml to match reality

- src/SayMore/UI/ComponentEditors/SessionBasicEditor.cs
This fixes issue #1 of SP-2353.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/210)
> SP-2353: Make pencil icon/button work to edit contributions in SessionBasicEditor

- src/SayMore/UI/ElementListScreen/ElementListScreen.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/212)
> SP-2354/SP-927: Fixed NullReferenceException

- build/SayMore.proj
- src/SayMore/SayMore.csproj
- src/SayMore/packages.config
Added missing target dependency
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/219)
> SP-2359: Upgraded to patched DesktopAnalytics

- src/SayMore/UI/ElementListScreen/ComponentFileGrid.cs
If current editor is not in a valid state to allow change, ignore mouse down.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/220)
> SP-2363: Prevent component file row change when invalid

- src/Installer/Installer.wxs
- src/SayMore/SayMore.csproj
- src/SayMore/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/221)
> Removed Analytics.dll, which we haven't been using for a long time

- src/SayMore/UI/ElementListScreen/ElementGrid.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/223)
> SP-2369: Prevent reentrant call to SetCurrentCellAddressCore

- src/SayMore/Transcription/UI/TextAnnotationGrid/TextAnnotationEditorGrid.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/224)
> SP-2365: Prevent deadlock caused by changing transcription cell during playback

- src/SayMore/MediaUtils/Audio/WaveControls/WaveControlBasic.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/227)
> SP-2370: Prevent NullReferenceException in HandlePlaybackMetering

- src/SayMore/UI/ElementListScreen/ComponentFileGrid.cs
- src/SayMore/UI/ElementListScreen/ElementListScreen.cs
- src/SayMore/UI/NewSessionsFromFiles/NewSessionsFromFilesDlg.cs
- src/SayMore/UI/Overview/ProjectDocsScreen.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/229)
> SP-2368: Prevent reentrant call to SetCurrentCellAddressCore

- src/SayMore/UI/ElementListScreen/ComponentFileGrid.cs
- src/SayMore/UI/ElementListScreen/ElementGrid.cs
- src/SayMore/UI/ElementListScreen/ElementListScreen.cs
- src/SayMoreTests/UI/ElementListScreen/ElementGridTests.cs
Removed previously added debug assertion that doesn't work as hoped. Remove dunused oldItem (ProjectElement) from SelectedElementChangedHandler
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/233)
> SP-2375: Plugged some potential re-entrancy holes in ElementGrid

- src/SayMore/UI/ComponentEditors/ContributorsEditor.cs
- src/SayMore/UI/ComponentEditors/EditorBase.cs
- src/SayMore/UI/ComponentEditors/NotesEditor.cs
- src/SayMore/UI/ComponentEditors/PersonBasicEditor.cs
- src/SayMore/UI/ComponentEditors/SessionBasicEditor.cs
- src/SayMore/UI/Overview/ProjectMetadataScreen.Designer.cs
- src/SayMore/UI/Overview/ProjectMetadataScreen.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/234)
> SP-2379: Fixed "SafeInvoke called before the control's handle was created"

- DistFiles/releaseNotes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/saymore/237)
> Updated releaseNotes.md to reflect generated 3.7.4 version and date
